name: deploy

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
env:
  env1: val1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker
        run: make docker-build

      - name: docker login
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

      - name: docker push
        run: make docker-push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: script
        run: |
          echo "script"
          cat ./deployments/ansible/requirements.yml
          ls deployments/ansible
        shell: bash

      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: deployments/ansible/playbook.yml
          inventory: deployments/ansible/inventory.ini
          galaxy_file: deployments/ansible/requirements.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://ulp.app
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false