name: deploy

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
env:
  env1: val1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker
        run: make docker-build

      - name: docker login
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

      - name: docker push
        run: make docker-push

  deploy:
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - uses: actions/checkout@v2

      - name: install Ansible
        run: |
          sudo apt-get update
          sudo apt install ansible
        shell: bash

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan ulp.com >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/github_actions

      - name: deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          make deploy
        shell: bash

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://ulp.app
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false