name: deploy

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: deploy to caprover
        run: make deploy-ci