name: deploy

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
env:
  env1: val1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker
        run: make docker-build

      - name: docker login
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

      - name: docker push
        run: make docker-push

  deploy:
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - uses: actions/checkout@v2

      - name: install Ansible
        run: |
          sudo apt-get update
          sudo apt install ansible
        shell: bash

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          known_hosts: unnecessary

      - name: deploy
        run: |
          make deploy
        shell: bash

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://ulp.app
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false